image: node:14.18.1

stages:         
  - build
  - deploy

cache:
  paths:
    - ~/node_modules

build-job:       
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-job:      
  stage: deploy  
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."